###################################################################

# Created by write_sdc on Fri Sep 25 02:56:18 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions -max scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -max_library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -min scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -min_library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c
set_wire_load_model -name tsmc13_wl30 -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports tx_rstn]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports rx_rstn]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports rx_in]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports rx_par_en]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports rx_par_typ]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {rx_prescale[5]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {rx_prescale[4]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {rx_prescale[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {rx_prescale[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {rx_prescale[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {rx_prescale[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports tx_par_en]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports tx_par_typ]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports fifo_rd_inc]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports tx_data_valid]
set_load -pin_load 0.1 [get_ports rx_stop_error]
set_load -pin_load 0.1 [get_ports rx_parity_error]
set_load -pin_load 0.1 [get_ports tx_out]
set_load -pin_load 0.1 [get_ports tx_busy]
set_load -pin_load 0.1 [get_ports fifo_full]
set_load -pin_load 0.1 [get_ports fifo_empty]
set_load -pin_load 0.1 [get_ports {fifo_rd_data[7]}]
set_load -pin_load 0.1 [get_ports {fifo_rd_data[6]}]
set_load -pin_load 0.1 [get_ports {fifo_rd_data[5]}]
set_load -pin_load 0.1 [get_ports {fifo_rd_data[4]}]
set_load -pin_load 0.1 [get_ports {fifo_rd_data[3]}]
set_load -pin_load 0.1 [get_ports {fifo_rd_data[2]}]
set_load -pin_load 0.1 [get_ports {fifo_rd_data[1]}]
set_load -pin_load 0.1 [get_ports {fifo_rd_data[0]}]
set_ideal_network [get_ports tx_rstn]
set_ideal_network [get_ports rx_rstn]
create_clock [get_ports rx_clk]  -name RX_CLK  -period 10  -waveform {0 5}
set_clock_latency 0  [get_clocks RX_CLK]
set_clock_uncertainty -setup 0.2  [get_clocks RX_CLK]
set_clock_uncertainty -hold 0.1  [get_clocks RX_CLK]
set_clock_transition -max -rise 0.05 [get_clocks RX_CLK]
set_clock_transition -min -rise 0.05 [get_clocks RX_CLK]
set_clock_transition -max -fall 0.05 [get_clocks RX_CLK]
set_clock_transition -min -fall 0.05 [get_clocks RX_CLK]
create_clock [get_ports tx_clk]  -name TX_CLK  -period 25  -waveform {0 12.5}
set_clock_latency 0  [get_clocks TX_CLK]
set_clock_uncertainty -setup 0.2  [get_clocks TX_CLK]
set_clock_uncertainty -hold 0.1  [get_clocks TX_CLK]
set_clock_transition -max -rise 0.05 [get_clocks TX_CLK]
set_clock_transition -min -rise 0.05 [get_clocks TX_CLK]
set_clock_transition -max -fall 0.05 [get_clocks TX_CLK]
set_clock_transition -min -fall 0.05 [get_clocks TX_CLK]
set_input_delay -clock RX_CLK  2  [get_ports rx_in]
set_input_delay -clock RX_CLK  2  [get_ports rx_par_en]
set_input_delay -clock RX_CLK  2  [get_ports rx_par_typ]
set_input_delay -clock RX_CLK  2  [get_ports {rx_prescale[5]}]
set_input_delay -clock RX_CLK  2  [get_ports {rx_prescale[4]}]
set_input_delay -clock RX_CLK  2  [get_ports {rx_prescale[3]}]
set_input_delay -clock RX_CLK  2  [get_ports {rx_prescale[2]}]
set_input_delay -clock RX_CLK  2  [get_ports {rx_prescale[1]}]
set_input_delay -clock RX_CLK  2  [get_ports {rx_prescale[0]}]
set_input_delay -clock RX_CLK  2  [get_ports rx_rstn]
set_input_delay -clock TX_CLK  5  [get_ports tx_par_en]
set_input_delay -clock TX_CLK  5  [get_ports tx_par_typ]
set_input_delay -clock TX_CLK  5  [get_ports fifo_rd_inc]
set_input_delay -clock TX_CLK  5  [get_ports tx_data_valid]
set_input_delay -clock TX_CLK  5  [get_ports tx_rstn]
set_output_delay -clock RX_CLK  2  [get_ports rx_stop_error]
set_output_delay -clock RX_CLK  2  [get_ports rx_parity_error]
set_output_delay -clock RX_CLK  2  [get_ports fifo_full]
set_output_delay -clock TX_CLK  5  [get_ports tx_out]
set_output_delay -clock TX_CLK  5  [get_ports tx_busy]
set_output_delay -clock TX_CLK  5  [get_ports fifo_empty]
set_output_delay -clock TX_CLK  5  [get_ports {fifo_rd_data[7]}]
set_output_delay -clock TX_CLK  5  [get_ports {fifo_rd_data[6]}]
set_output_delay -clock TX_CLK  5  [get_ports {fifo_rd_data[5]}]
set_output_delay -clock TX_CLK  5  [get_ports {fifo_rd_data[4]}]
set_output_delay -clock TX_CLK  5  [get_ports {fifo_rd_data[3]}]
set_output_delay -clock TX_CLK  5  [get_ports {fifo_rd_data[2]}]
set_output_delay -clock TX_CLK  5  [get_ports {fifo_rd_data[1]}]
set_output_delay -clock TX_CLK  5  [get_ports {fifo_rd_data[0]}]
set_clock_groups -asynchronous -name RX_CLK_1 -group [get_clocks RX_CLK] -group [get_clocks TX_CLK]
